Repository litmuschaos/litmus-helm, pull requests merged in 2021-04, with the labels that each got.

#100 Fix incompatibility when install to GKE
  charts/litmus-2-0-0-beta/Chart.yaml
  charts/litmus-2-0-0-beta/README.md
Labels: bug

#106 Adding envs for ns scope and argo's container runtime executor.
  charts/litmus-2-0-0-beta/Chart.yaml
  charts/litmus-2-0-0-beta/README.md
  charts/litmus-2-0-0-beta/values.yaml
Labels: enhancement

#108 Adding HUB_BRANCH_NAME env. for server
  charts/litmus-2-0-0-beta/Chart.yaml
  charts/litmus-2-0-0-beta/README.md
  charts/litmus-2-0-0-beta/values.yaml
Labels: enhancement

#111 Litmus 2.0 beta docs link fix and charts version bumped.
  charts/litmus-2-0-0-beta/Chart.yaml
  charts/litmus-2-0-0-beta/README.md
  charts/litmus-2-0-0-beta/templates/NOTES.txt
Labels: bug-fix

#116 Fixes for ns scope (elevating permissions for portal server)
  charts/litmus-2-0-0-beta/Chart.yaml
  charts/litmus-2-0-0-beta/README.md
  charts/litmus-2-0-0-beta/templates/server-role.yaml
Labels: bug-fix
