Repository litmuschaos/litmus-helm, pull requests merged in 2021-03, with the labels that each got.

#91 Fix service, improve CI
  .github/CODEOWNERS
  .pre-commit-config.yaml
  charts/kubernetes-chaos/Chart.yaml
  charts/kubernetes-chaos/README.md
  charts/litmus-2-0-0-beta/Chart.yaml
  charts/litmus-2-0-0-beta/README.md
  charts/litmus-2-0-0-beta/templates/frontend-svc.yaml
  charts/litmus-2-0-0-beta/templates/server-svc.yaml
  charts/litmus/Chart.yaml
  charts/litmus/README.md
Labels: bug, enhancement

#92 Add deploy tests
  .circleci/config.yml
  .github/CODEOWNERS
  README.md
  charts/kubernetes-chaos/Chart.yaml
  charts/kubernetes-chaos/README.md
  charts/litmus-2-0-0-beta/Chart.yaml
  charts/litmus-2-0-0-beta/README.md
  charts/litmus/Chart.yaml
  charts/litmus/README.md
Labels: enhancement

#97 Adding self cluster as a env in charts
  charts/litmus-2-0-0-beta/Chart.yaml
  charts/litmus-2-0-0-beta/README.md
  charts/litmus-2-0-0-beta/templates/server-deployment.yaml
  charts/litmus-2-0-0-beta/values.yaml
Labels: feature
